### PR TITLE
Add unit test project.

### PR DESCRIPTION
**Pull request by jciechowski**
I've added project with unit test using .net core 2.0 and xunit regarding issue #2 
Tests are really simple but I hope you will make use of it anyway.

[I've changed one thing in your code](https://github.com/shrayasr/pinboard.net/compare/master...jciechowski:core_unit_tests?expand=1#diff-d58a1d9b3fbb2da031980f82322f6747) - instead of List TagsConverter now casts to IEnumerable.

Feel free to comment!

### CODE REVIEW

**Comment by shrayasr** [comment]
Thanks for this 👏 I will have a look today

**Comment by shrayasr** [comment]
For a first cut, this is awesome. Appreciate it. Thanks! :)

**Comment by jciechowski** [comment]
Agree, it's nothing fancy.
I can work on coverage though. If you want to unit test some part of code just create an issue or contact me via email.

**Comment by shrayasr** [comment]
Preferably all parts of the code need to be tested. I'm quite held up at work to put any more hours into this but if you have some time, you're more than welcome to send more PRs 😄

**Comment by jciechowski** [comment]
Is it ok if in the process I do some refactoring? It's your code and your project so I don't want to interfere too much

**Comment by shrayasr** [comment]
Its open source for a reason 🙌 

As long as it makes sense, I'm OK with it.

**Pull request merged**
