### PR TITLE
Added project with some unit tests

### PR DESCRIPTION
**Pull request by jciechowski**
Regarding issue #2 I've created project with unit tests using nunit and sadly .net framework (had some problem with running nunit on .net standard).
There are only a few tests but maybe this project will help you to add your own.
Feel free to leave comments or contact me if you need any help.

### CODE REVIEW

**Comment by shrayasr** [comment]
This is awesome 👏 ✨Thanks so much for taking time out and sending this in.

Although I'd prefer to not mix .net framework with .net standard. I know that [xunit](https://xunit.github.io/) supports .net standard. Would it be possible for you to rewrite these tests using xunit instead?

**Comment by jciechowski** [comment]
Ye, of course. Will try to do that in a few days.
In that case you can close this PR and I will create a new one.

**Comment by shrayasr** [comment]
Awesome. Thank you :)

**Comment by jciechowski** [comment]
I've just googled and played a bit with xunit and .net standard and can't find way to run it.
It looks like it works only with .net core. Is core ok for you?

**Comment by shrayasr** [comment]
.net standard isn't a framework. Its more a specification of what APIs should go into which framework version.

Since the main project (`pinboard.net`) itself doesn't take full framework dependency, it didn't make sense for me to target the full framework just for nunit tests. 

So yes, having a `pinboard.net.tests` as a .net core project works for me 👍 

Hope the thought process is clear? Feel free to probe :)

**Pull request closed without merging**
